class AppStrings {
  static String locale = 'vi'; // 'vi' hoặc 'en'
  
  static final Map<String, Map<String, String>> _strings = {
    // Common
    'appTitle': {'vi': 'SOS App UTH', 'en': 'SOS App UTH'},
    'cancel': {'vi': 'Hủy', 'en': 'Cancel'},
    'confirm': {'vi': 'Xác nhận', 'en': 'Confirm'},
    'save': {'vi': 'Lưu', 'en': 'Save'},
    'close': {'vi': 'Đóng', 'en': 'Close'},
    'loading': {'vi': 'Đang tải...', 'en': 'Loading...'},
    'error': {'vi': 'Lỗi', 'en': 'Error'},
    'success': {'vi': 'Thành công', 'en': 'Success'},
    'or': {'vi': 'Hoặc', 'en': 'Or'},
    
    // Auth
    'login': {'vi': 'Đăng Nhập', 'en': 'Login'},
    'signup': {'vi': 'Đăng Ký', 'en': 'Sign Up'},
    'welcome': {'vi': 'Chào mừng bạn!', 'en': 'Welcome!'},
    'email': {'vi': 'Email', 'en': 'Email'},
    'emailOrPhone': {'vi': 'Email hoặc số điện thoại', 'en': 'Email or phone number'},
    'password': {'vi': 'Mật khẩu', 'en': 'Password'},
    'rememberMe': {'vi': 'Ghi nhớ', 'en': 'Remember me'},
    'forgotPassword': {'vi': 'Quên mật khẩu?', 'en': 'Forgot password?'},
    'loginWithGoogle': {'vi': 'Đăng nhập với Google', 'en': 'Sign in with Google'},
    'loginSuccess': {'vi': 'Đăng nhập thành công ✅', 'en': 'Login successful ✅'},
    'loginError': {'vi': 'Sai thông tin đăng nhập ❌', 'en': 'Invalid credentials ❌'},
    'noAccount': {'vi': 'Chưa có tài khoản? ', 'en': "Don't have an account? "},
    'signupNow': {'vi': 'Đăng ký ngay', 'en': 'Sign up now'},
    'pleaseEnterInfo': {'vi': 'Vui lòng nhập thông tin', 'en': 'Please enter information'},
    
    // Signup
    'signUp': {'vi': 'Đăng Ký', 'en': 'Sign Up'},
    'alreadyHaveAccount': {'vi': 'Bạn đã có tài khoản?', 'en': 'Already have an account?'},
    'signUpButton': {'vi': 'Đăng Ký', 'en': 'Sign Up'},
    'or': {'vi': 'Hoặc', 'en': 'Or'},
    'signInWithGoogle': {'vi': 'Đăng nhập với Google', 'en': 'Sign in with Google'},
    'signupSuccess': {'vi': 'Đăng ký thành công ✅', 'en': 'Sign up successful ✅'},
    'signupFailed': {'vi': 'Đăng ký thất bại!', 'en': 'Sign up failed!'},
    'signupError': {'vi': 'Lỗi đăng ký', 'en': 'Sign up error'},
    'phoneLength': {'vi': 'Số điện thoại phải có 10 chữ số', 'en': 'Phone must be 10 digits'},
    'phoneStartZero': {'vi': 'Số điện thoại phải bắt đầu bằng số 0', 'en': 'Phone must start with 0'},
    
    // Settings
    'settings': {'vi': 'Cài đặt', 'en': 'Settings'},
    'darkMode': {'vi': 'Chế độ tối', 'en': 'Dark Mode'},
    'darkModeOn': {'vi': 'Đang bật', 'en': 'Enabled'},
    'darkModeOff': {'vi': 'Đang tắt', 'en': 'Disabled'},
    'language': {'vi': 'Ngôn ngữ', 'en': 'Language'},
    'vietnamese': {'vi': 'Tiếng Việt', 'en': 'Vietnamese'},
    'english': {'vi': 'Tiếng Anh', 'en': 'English'},
    'selectLanguage': {'vi': 'Chọn ngôn ngữ', 'en': 'Select Language'},
    
    // Navigation
    'home': {'vi': 'Trang chủ', 'en': 'Home'},
    'activity': {'vi': 'Hoạt động', 'en': 'Activity'},
    'sos': {'vi': 'SOS', 'en': 'SOS'},
    'profile': {'vi': 'Hồ sơ', 'en': 'Profile'},
    
    // Account Page
    'noBioYet': {'vi': 'Chưa có giới thiệu bản thân', 'en': 'No bio yet'},
    'noYearOfBirth': {'vi': 'Chưa cập nhật năm sinh', 'en': 'Year not updated'},
    'editBio': {'vi': 'Chỉnh sửa giới thiệu', 'en': 'Edit bio'},
    'enterBio': {'vi': 'Nhập giới thiệu về bạn...', 'en': 'Enter your bio...'},
    'bioUpdated': {'vi': 'Đã cập nhật giới thiệu', 'en': 'Bio updated'},
    'uploading': {'vi': 'Đang tải lên...', 'en': 'Uploading...'},
    'changeAvatar': {'vi': 'Đổi ảnh đại diện', 'en': 'Change avatar'},
    'avatarUpdated': {'vi': 'Đã cập nhật ảnh đại diện', 'en': 'Avatar updated'},
    'myProfile': {'vi': 'Hồ sơ', 'en': 'Profile'},
    'viewEditInfo': {'vi': 'Xem và chỉnh sửa thông tin', 'en': 'View and edit info'},
    'volunteerStatus': {'vi': 'Trạng thái hoạt động', 'en': 'Activity status'},
    'readyForRequests': {'vi': 'Đang sẵn sàng nhận yêu cầu', 'en': 'Ready for requests'},
    'notReceivingSOS': {'vi': 'Tắt nhận yêu cầu SOS', 'en': 'Not receiving SOS'},
    'viewVolunteerProfile': {'vi': 'Xem hồ sơ tình nguyện viên', 'en': 'View volunteer profile'},
    'manageVolunteerProfile': {'vi': 'Quản lý hồ sơ TNV của bạn', 'en': 'Manage your volunteer profile'},
    'pendingApproval': {'vi': 'Hồ sơ đang chờ duyệt', 'en': 'Profile pending approval'},
    'waitForAdmin': {'vi': 'Vui lòng chờ quản trị viên xác nhận', 'en': 'Please wait for admin confirmation'},
    'underReview': {'vi': 'Đang xét duyệt', 'en': 'Under review'},
    'registrationRejected': {'vi': 'Đăng ký bị từ chối', 'en': 'Registration rejected'},
    'tapToReregister': {'vi': 'Nhấn để đăng ký lại', 'en': 'Tap to re-register'},
    'becomeVolunteer': {'vi': 'Đăng ký làm tình nguyện viên', 'en': 'Become a volunteer'},
    'joinRescueCommunity': {'vi': 'Tham gia cứu hộ cộng đồng', 'en': 'Join rescue community'},
    'customizeApp': {'vi': 'Tùy chỉnh ứng dụng', 'en': 'Customize app'},
    'createPost': {'vi': 'Đăng bài viết', 'en': 'Create post'},  
    'createPostSubtitle': {'vi': 'Tạo bài viết mới cho cộng đồng', 'en': 'Create new post for community'},
    'aboutApp': {'vi': 'Về ứng dụng', 'en': 'About app'},
    'versionInfo': {'vi': 'Thông tin phiên bản', 'en': 'Version info'},
    'sosRequestOn': {'vi': 'Đã bật nhận yêu cầu SOS', 'en': 'SOS requests enabled'},
    'sosRequestOff': {'vi': 'Đã tắt nhận yêu cầu SOS', 'en': 'SOS requests disabled'},
    
    // SOS
    'sosEmergency': {'vi': 'Khẩn Cấp SOS', 'en': 'SOS Emergency'},
    'sosNotYet': {'vi': 'Chưa', 'en': 'Not yet'},
    'sosComplete': {'vi': 'Hoàn thành', 'en': 'Complete'},
    'sosCompleteSuccess': {'vi': 'Đã hoàn thành ứng cứu thành công!', 'en': 'Rescue completed successfully!'},
    'backToHome': {'vi': 'Về trang chủ', 'en': 'Back to home'},
    'victimInfo': {'vi': 'Thông tin người cần cứu', 'en': 'Victim information'},
    'cannotOpenMaps': {'vi': 'Không thể mở Google Maps', 'en': 'Cannot open Google Maps'},
    
    // SOS Emergency Screen
    'emergencyRescue': {'vi': 'Cứu hộ khẩn cấp', 'en': 'Emergency Rescue'},
    'sosDescription': {'vi': 'Gửi vị trí và thông tin sự cố ngay lập tức.\nĐội cứu hộ sẽ hỗ trợ bạn.', 'en': 'Send location and incident information instantly.\nRescue team will assist you.'},
    'detailsInfo': {'vi': 'Thông tin chi tiết', 'en': 'Details'},
    'fullNameRequired': {'vi': 'Họ và tên của bạn (*)', 'en': 'Your full name (*)'},
    'describeIncident': {'vi': 'Mô tả sự cố / Ghi chú thêm...', 'en': 'Describe incident / Additional notes...'},
    'sendNow': {'vi': 'GỬI NGAY', 'en': 'SEND NOW'},
    'holdToSend': {'vi': 'Giữ 3 giây để gửi', 'en': 'Hold 3 seconds to send'},
    'yourLocation': {'vi': 'Vị trí của bạn', 'en': 'Your location'},
    
    // Emergency Types
    'medical': {'vi': 'Y tế', 'en': 'Medical'},
    'fire': {'vi': 'Cháy nổ', 'en': 'Fire'},
    'accident': {'vi': 'Tai nạn', 'en': 'Accident'},
    'crime': {'vi': 'Trộm cắp', 'en': 'Crime'},
    'naturalDisaster': {'vi': 'Thiên tai', 'en': 'Natural Disaster'},
    'other': {'vi': 'Khác', 'en': 'Other'},
    
    // Validation & Messages
    'pleaseEnableLoc': {'vi': 'Vui lòng bật dịch vụ vị trí', 'en': 'Please enable location service'},
    'locPermissionDenied': {'vi': 'Quyền truy cập vị trí bị từ chối', 'en': 'Location permission denied'},
    'locPermissionPermanent': {'vi': 'Quyền truy cập vị trí bị từ chối vĩnh viễn', 'en': 'Location permission permanently denied'},
    'locUpdated': {'vi': 'Đã cập nhật vị trí hiện tại', 'en': 'Current location updated'},
    'errorGettingLoc': {'vi': 'Lỗi khi lấy vị trí', 'en': 'Error getting location'},
    'pleaseEnterName': {'vi': 'Vui lòng nhập tên của bạn', 'en': 'Please enter your name'},
    'pleaseGetLocFirst': {'vi': 'Vui lòng lấy vị trí hiện tại trước', 'en': 'Please get current location first'},
    'sosSentSuccess': {'vi': 'Đã gửi tín hiệu SOS thành công!', 'en': 'SOS signal sent successfully!'},
    'requestRejected': {'vi': 'Yêu cầu bị từ chối', 'en': 'Request rejected'},
    'errorSendingSos': {'vi': 'Lỗi gửi SOS', 'en': 'Error sending SOS'},
    
    // Home Page
    'you': {'vi': 'Bạn', 'en': 'You'},
    'hello': {'vi': 'Xin chào', 'en': 'Hello'},
    'goodMorning': {'vi': 'Chúc bạn sáng vui vẻ', 'en': 'Good morning'},
    'goodAfternoon': {'vi': 'Chúc bạn chiều vui vẻ', 'en': 'Good afternoon'},
    'goodEvening': {'vi': 'Chúc bạn tối vui vẻ', 'en': 'Good evening'},
    'justNow': {'vi': 'Vừa xong', 'en': 'Just now'},
    'minutesAgo': {'vi': 'phút trước', 'en': 'minutes ago'},
    'minuteAgo': {'vi': 'phút trước', 'en': 'minute ago'},
    'hoursAgo': {'vi': 'giờ trước', 'en': 'hours ago'},
    'hourAgo': {'vi': 'giờ trước', 'en': 'hour ago'},
    'daysAgo': {'vi': 'ngày trước', 'en': 'days ago'},
    'dayAgo': {'vi': 'ngày trước', 'en': 'day ago'},
    'weatherAt': {'vi': 'Thời tiết tại', 'en': 'Weather at'},
    'rain': {'vi': 'Mưa', 'en': 'Rain'},
    'wind': {'vi': 'Gió', 'en': 'Wind'},
    'news': {'vi': 'Bản tin', 'en': 'News'},
    'solarDate': {'vi': 'DL', 'en': 'Solar'},
    'lunarDate': {'vi': 'ÂL', 'en': 'Lunar'},
    'noPosts': {'vi': 'Chưa có bài viết nào', 'en': 'No posts yet'},
    'cannotLoadWeather': {'vi': 'Không thể tải thông tin thời tiết', 'en': 'Cannot load weather'},
    'viewDetails': {'vi': 'Xem chi tiết', 'en': 'View details'},
    'cannotUpdateLike': {'vi': 'Không thể cập nhật lượt thích', 'en': 'Cannot update like'},
    'errorLoadingImage': {'vi': 'Lỗi tải ảnh', 'en': 'Error loading image'},
    
    // Account Screen
    'personalInfo': {'vi': 'Thông tin cá nhân', 'en': 'Personal Information'},
    'fullName': {'vi': 'Họ và tên', 'en': 'Full name'},
    'phoneNumber': {'vi': 'Số điện thoại', 'en': 'Phone number'},
    'dateOfBirth': {'vi': 'Ngày sinh', 'en': 'Date of birth'},
    'role': {'vi': 'Vai trò', 'en': 'Role'},
    'userId': {'vi': 'User ID', 'en': 'User ID'},
    'security': {'vi': 'Bảo mật', 'en': 'Security'},
    'changePassword': {'vi': 'Đổi mật khẩu', 'en': 'Change password'},
    'deleteAccount': {'vi': 'Xóa tài khoản', 'en': 'Delete account'},
    'logout': {'vi': 'Đăng xuất', 'en': 'Logout'},
    'notUpdated': {'vi': 'Chưa cập nhật', 'en': 'Not updated'},
    'emailNotUpdated': {'vi': 'Email chưa cập nhật', 'en': 'Email not updated'},
    'user': {'vi': 'Người dùng', 'en': 'User'},
    'dobUpdated': {'vi': 'Đã cập nhật ngày sinh', 'en': 'Date of birth updated'},
    'cannotLoadProfile': {'vi': 'Không thể tải thông tin hồ sơ', 'en': 'Cannot load profile'},
    'unknownError': {'vi': 'Lỗi không xác định', 'en': 'Unknown error'},
    'retry': {'vi': 'Thử lại', 'en': 'Retry'},
    
    // Volunteer Registration
    'volunteerRegistration': {'vi': 'Đăng ký Tình nguyện viên', 'en': 'Volunteer Registration'},
    'basicInfo': {'vi': 'Thông tin cơ bản', 'en': 'Basic Information'},
    'participationType': {'vi': 'Loại hình tham gia', 'en': 'Participation Type'},
    'individual': {'vi': 'Cá nhân', 'en': 'Individual'},
    'organization': {'vi': 'Tổ chức', 'en': 'Organization'},
    'organizationName': {'vi': 'Tên tổ chức', 'en': 'Organization Name'},
    'pleaseEnterOrgName': {'vi': 'Vui lòng nhập tên tổ chức', 'en': 'Please enter organization name'},
    'supportSkills': {'vi': 'Kỹ năng hỗ trợ', 'en': 'Support Skills'},
    'rescue': {'vi': 'Cứu hộ', 'en': 'Rescue'},
    'vehicleRepair': {'vi': 'Sửa xe', 'en': 'Vehicle Repair'},
    'transport': {'vi': 'Vận chuyển', 'en': 'Transport'},
    'essentials': {'vi': 'Nhu yếu phẩm', 'en': 'Essentials'},
    'counseling': {'vi': 'Tư vấn tâm lý', 'en': 'Counseling'},
    'identityVerification': {'vi': 'Xác minh danh tính', 'en': 'Identity Verification'},
    'uploadIdInstruction': {'vi': 'Vui lòng tải lên ảnh CCCD/CMND hoặc giấy tờ liên quan', 'en': 'Please upload ID card or related documents'},
    'frontSide': {'vi': 'Mặt trước', 'en': 'Front Side'},
    'backSide': {'vi': 'Mặt sau', 'en': 'Back Side'},
    'uploadPhoto': {'vi': 'Tải ảnh lên', 'en': 'Upload Photo'},
    'commitment': {'vi': 'Tôi cam kết các thông tin trên là chính xác và chịu trách nhiệm về hoạt động tình nguyện của mình.', 'en': 'I commit that the above information is accurate and I am responsible for my volunteer activities.'},
    'submitRegistration': {'vi': 'Gửi Đăng Ký', 'en': 'Submit Registration'},
    'registrationSuccess': {'vi': 'Đăng ký thành công', 'en': 'Registration Successful'},
    'registrationPending': {'vi': 'Hồ sơ của bạn đã được gửi và đang chờ duyệt. Chúng tôi sẽ thông báo cho bạn sớm nhất.', 'en': 'Your application has been submitted and is pending review. We will notify you soon.'},
    'selectAtLeastOneSkill': {'vi': 'Vui lòng chọn ít nhất 1 kỹ năng', 'en': 'Please select at least 1 skill'},
    'uploadBothSides': {'vi': 'Vui lòng tải lên đủ 2 mặt giấy tờ', 'en': 'Please upload both sides of the document'},
    'agreeToTerms': {'vi': 'Vui lòng đồng ý với điều khoản', 'en': 'Please agree to the terms'},
    'userNotFound': {'vi': 'Không tìm thấy thông tin user', 'en': 'User information not found'},
    'errorPickingImage': {'vi': 'Lỗi chọn ảnh', 'en': 'Error picking image'},
  };
  
  // Lấy string theo key
  static String get(String key) {
    return _strings[key]?[locale] ?? key;
  }
  
  // Đổi ngôn ngữ
  static void setLocale(String newLocale) {
    locale = newLocale;
  }
}
